services:
  - type: web
    name: mainevents
    env: node
    buildCommand: ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    build:
      nodeVersion: 18.x
